[dev]
type = "conf/DEV"

[mysql_main]
host = "127.0.0.1:3306"
database = "fun_anime_server"
user = "root"
password = "123456"

[redis_main]
host = "127.0.0.1:6379"

[redis]
host = "127.0.0.1:6379"

[secret_key]
key = "sinblog.cn"
password_key = "123456"